name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - next
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get tag version
      id: prep
      run: |
        if [[ $GITHUB_REF == refs/heads/main ]]; then
          echo "version=latest" >> $GITHUB_OUTPUT
        elif [[ $GITHUB_REF == refs/heads/next ]]; then
          echo "version=nightly" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/url-to-png:${{ steps.prep.outputs.version }}
          ${{ secrets.DOCKERHUB_USER }}/url-to-png:${{ steps.prep.outputs.version }}
